# Generated by Drydock — static site (built with node, served by bun).
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM oven/bun:1.3-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/dist ./public
RUN printf '%s\n' \
  'const root = new URL("./public/", import.meta.url).pathname;' \
  'const port = Number(process.env.PORT ?? 3000);' \
  'Bun.serve({ port, async fetch(req) {' \
  '  const url = new URL(req.url);' \
  '  let p = decodeURIComponent(url.pathname);' \
  '  if (p.endsWith("/")) p += "index.html";' \
  '  let file = Bun.file(root + p.replace(/^\//, ""));' \
  '  if (!(await file.exists())) file = Bun.file(root + "index.html");' \
  '  return new Response(file);' \
  '} });' \
  'console.log("static server on " + port);' > serve.ts
EXPOSE 3000
CMD ["bun", "serve.ts"]
